"""Update room module schema

Revision ID: 17df179fc3ef
Revises: 71360d32622c
Create Date: 2026-07-27 15:48:06.130383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17df179fc3ef'
down_revision: Union[str, Sequence[str], None] = '71360d32622c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_images', sa.Column('room_type_id', sa.UUID(), nullable=False))
    op.add_column('room_images', sa.Column('caption', sa.String(length=255), nullable=True))
    op.add_column('room_images', sa.Column('is_cover', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_room_images_room_id'), table_name='room_images')
    op.create_index(op.f('ix_room_images_room_type_id'), 'room_images', ['room_type_id'], unique=False)
    op.drop_constraint(op.f('room_images_room_id_fkey'), 'room_images', type_='foreignkey')
    op.create_foreign_key(None, 'room_images', 'room_types', ['room_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('room_images', 'image_name')
    op.drop_column('room_images', 'room_id')
    op.drop_column('room_images', 'is_primary')
    op.drop_column('room_images', 'image_type')
    op.add_column('room_types', sa.Column('room_name', sa.String(length=150), nullable=False))
    op.add_column('room_types', sa.Column('max_adults', sa.Integer(), nullable=False))
    op.add_column('room_types', sa.Column('max_children', sa.Integer(), nullable=False))
    op.add_column('room_types', sa.Column('room_size_sqm', sa.Numeric(precision=6, scale=2), nullable=True))
    op.drop_constraint(op.f('uq_property_room_type'), 'room_types', type_='unique')
    op.create_unique_constraint('uq_property_room_type', 'room_types', ['property_id', 'room_name'])
    op.drop_column('room_types', 'name')
    op.drop_column('room_types', 'max_occupancy')
    op.drop_column('room_types', 'size_sqm')
    op.add_column('rooms', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column(
        "rooms",
        "floor",
    )

    op.add_column(
        "rooms",
        sa.Column(
            "floor",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.drop_index(op.f('ix_rooms_property_id'), table_name='rooms')
    op.drop_constraint(op.f('uq_property_room_number'), 'rooms', type_='unique')
    op.create_unique_constraint('uq_property_room_number', 'rooms', ['room_type_id', 'room_number'])
    op.drop_constraint(op.f('rooms_property_id_fkey'), 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'property_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('rooms_property_id_fkey'), 'rooms', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_property_room_number', 'rooms', type_='unique')
    op.create_unique_constraint(op.f('uq_property_room_number'), 'rooms', ['property_id', 'room_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_rooms_property_id'), 'rooms', ['property_id'], unique=False)
    op.alter_column('rooms', 'floor',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('rooms', 'is_active')
    op.add_column('room_types', sa.Column('size_sqm', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('room_types', sa.Column('max_occupancy', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('room_types', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint('uq_property_room_type', 'room_types', type_='unique')
    op.create_unique_constraint(op.f('uq_property_room_type'), 'room_types', ['property_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('room_types', 'room_size_sqm')
    op.drop_column('room_types', 'max_children')
    op.drop_column('room_types', 'max_adults')
    op.drop_column('room_types', 'room_name')
    op.add_column('room_images', sa.Column('image_type', postgresql.ENUM('ROOM', 'BATHROOM', 'BALCONY', 'VIEW', 'OTHER', name='roomimagetype'), autoincrement=False, nullable=False))
    op.add_column('room_images', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('room_images', sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('room_images', sa.Column('image_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'room_images', type_='foreignkey')
    op.create_foreign_key(op.f('room_images_room_id_fkey'), 'room_images', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_room_images_room_type_id'), table_name='room_images')
    op.create_index(op.f('ix_room_images_room_id'), 'room_images', ['room_id'], unique=False)
    op.drop_column('room_images', 'is_cover')
    op.drop_column('room_images', 'caption')
    op.drop_column('room_images', 'room_type_id')
    # ### end Alembic commands ###
