"""change created_by updated_by to email

Revision ID: ec237d86dbe6
Revises: 7a62fc832732
Create Date: 2026-07-24 13:46:57.935930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec237d86dbe6'
down_revision: Union[str, Sequence[str], None] = '7a62fc832732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('addresses', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('amenities', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('amenities', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('booking_cancellations', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('booking_cancellations', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('booking_history', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('booking_history', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('booking_rooms', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('booking_rooms', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('bookings', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('bookings', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('favorites', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('favorites', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('invoices', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('payments', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('payments', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('permissions', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('permissions', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('properties', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('properties', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('property_amenities', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('property_amenities', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('property_images', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('property_images', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('role_permissions', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('role_permissions', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('roles', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('roles', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('room_amenities', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('room_amenities', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('room_images', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('room_images', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('room_types', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('room_types', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('rooms', sa.Column('property_id', sa.UUID(), nullable=False))
    op.alter_column('rooms', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('rooms', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_rooms_property_id'), 'rooms', ['property_id'], unique=False)
    op.create_foreign_key(None, 'rooms', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_property_id'), table_name='rooms')
    op.alter_column('rooms', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('rooms', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('rooms', 'property_id')
    op.alter_column('room_types', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('room_types', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('room_images', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('room_images', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('room_amenities', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('room_amenities', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('roles', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('roles', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('role_permissions', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('role_permissions', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('property_images', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('property_images', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('property_amenities', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('property_amenities', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('properties', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('properties', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('permissions', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('permissions', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('payments', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('payments', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('invoices', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('invoices', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('favorites', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('favorites', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('bookings', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('bookings', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('booking_rooms', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('booking_rooms', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('booking_history', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('booking_history', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('booking_cancellations', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('booking_cancellations', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('amenities', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('amenities', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('addresses', 'updated_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('addresses', 'created_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
